on: ["pull_request"]

name: Test Coverage

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: yarn install, yarn test:coverage
      run: |
        yarn install
        yarn test --coverage

    - name: Coverage
      uses: romeovs/lcov-reporter-action@v0.4.0
      with:
        lcov-file: ./coverage/lcov.info
