on:
  push:
    branches:
      - main

name: Test with Coveralls
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 10.34.4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: pnpm

    - name: pnpm install, pnpm test:coverage
      run: |
        pnpm install --frozen-lockfile
        echo repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }} > .coveralls.yml
        pnpm run test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
